<div class="yui-g">
<h1>We help you communicate with your elected representatives.</h1>
<h2>Mission Statement</h2>

<p>The mission of ItsYourIssue.com, a unique internet utility, is to provide a thus-far unfulfilled, easily utilized, and desperately needed communications channel between concerned citizens and their government representatives and/or the media. As people review the multitude of web sites that provide news/views about political, social, economic, and domestic/foreign policy issues, many feel an urgent need to rise up and shout "NO." Now, ItsYourIssue.com can be the no-cost vehicle for all of them to quickly and efficiently reach their representatives in order to communicate their questions, demands and complaints.</p>

<h2>The Issues</h2>

<p>Americans are living in a period of transition, and millions of them are uneasy about the changes they see. Worse yet, they feel frustrated and impotent because there is no easy way to communicate their concerns. The very segment of the population that should have the most influence in determining government policies--working Americans--are the people who participate the least. Few of them have time to research facts about an issue; write a cogent, well-informed letter, and learn how and where to send it. They don't have time, and they don't want to wait for their views to get to their representatives, because they want to make a difference now! </p>
 
<p>Currently, thousands of special-interest web sites and blogs focus on--and are generally well-informed about--a few specific issues. Their purpose is to influence public opinion so that people will be motivated to contact their representatives with their demands, and thus affect public policy. However, some of those web sites charge a significant amount of money to send out prepared faxes; others ask you to sign a petition which they will email; while many plead for viewers to write letters to fax or mail, or even to make telephone calls to their representatives. None of these methods are self-satisfying or very effective in achieving their goals. The result is that our representatives live in a bubble dominated by their party constituents, lobbyists and well-funded special interest groups. We, the people, are left out of the loop.</p>

<p>Before the creation of ItsYourIssue.com, there was no existing framework for time-strapped citizens to reach their politicians or the media. That has changed, as ItsYourIssue.com provides a free, powerful tool for all web sites to influence government policy by making it very easy for their readers to learn about the issues and then contact their representatives. Every American can deluge their representatives with their requests and/or demands, and then they can make a difference. </p>

<h2>The Model </h2>

<p>ItsYourIssue.com uses a unique, dynamic, multi-layered advertising model that allows its use to be free to all. The use of an open-source model (such as Wikipedia) will keep the content current with evolving events and issues, and will make this site very attractive to use for anyone concerned about government actions, bills or policies. An added attraction is that the site will make it easy, fast and efficient for citizens to communicate their concerns to their elected representatives as well as to the media. This will emphasize the messages that Americans are sending to every level of government--from national, state, and district--down to county and city. </p>
 
<p>Discrete page generation for each individual user will allow the most relevant and concise advertising targeted to the user as he moves from issue to issue and through each political level, from national to local. A separate banner or column for advertisers will appear at the top and/or bottom of each issue page and every letter page referring to each issue at every political level.</p>

<p>Advertising on each layer will be targeted to the users' interests, gender and geographical location; so that interest-specific advertising will follow users clear down to the city or town level. The Second Amendment issue makes a good example: Southern states' users interested in border security might see advertising from insurance companies at the national level, private security companies at the state level, lawyers at the district level, and gun shops at the county and city level. A variety of the ads could be placed on the Article pages as well. We believe that this targeted, multi-layered advertising model will be very compelling for a wide and diversified advertising base. The dynamic, diversified and actionable content will ensure a very high level of consistent traffic. </p>

<h2>Nuts And Bolts </h2>

<p>ItsYourIssue.com provides a forum for blogs, informational sites, news sites and special interest sites of all political persuasions to compete in the arena of ideologies. The users will be able to compare issues information between their own political philosophy and several others to determine the views that best fits his or her values. </p>

<p>Any web site interested in shaping public opinion or policy can provide an ItsYourIssue link button at the end of any particular article. If a reader clicks on it, the site then leads to a number of interactive letters emphasizing that belief system for the viewer to choose from, to modify, and to add personal contact information. Another link opens to each viewer's personal page of political representatives at all levels, complete with all contact information. There, they can choose to send the letter supporting their particular point of view to any number of their representatives via email and/or fax, as well as to local or national media and to themselves. </p>

<p>We believe that some people will go to ItsYourIssue.com for the purpose of communicating with their representatives about specific issues that have been in the news or that they are passionate about. They may want to view the status of current issues, and to compare the competing letters about these issues. 
The home page of ItsYourIssue.com directs a new user to register, for which a sign-up box opens in a new, secure window to insert personal information, including their email address, a password and the zip code. A user who logs in with that information is forwarded to a page with a current list of national issues' links on one side, and his own State, District, County and City links on the other side. (The local information would be automated by each user's zip code.)</p>

<p>If he is interested in a national issue and clicks on--say--The Second Amendment link, he would find a short definition of the Second Amendment, the current issues involving it, and any related information. By clicking on a link on that page to Articles, the user would see a choice of several articles on the issue. If he wants more information on the subject, he can read two or more articles.</p>

<p>A list of competing open-source letters on this issue (with title links) would be included in a side column on each Articles page. Each title, when clicked on, would open into a full-sized window. The user could then read one or (by returning to the previous list) a series of current letters written by people who wish to influence government policy in one direction or another. The letters would be event driven. Some letters would be contributed by well-known writers and commentators. Most would come from blogs, special interest sites, or political sites. The source of the letters will always be displayed to the users, so the user can better assess bias and validity. No letters will be displayed unless they can be sourced to a specific writer. The site's interactive provisions allow a user to modify a chosen letter to give it a personal touch and their contact information before it is sent to the intended targets, whether those are political representatives or media commentators.</p>

<p>In a box at the bottom of each letter, two link buttons are titled: Representatives and Media. When--say--the member clicks on Representatives, another window will open with all his personal National, State, District, County and City representatives listed, along with their titles, email addresses, phone and fax numbers, and mailing address. Next to the email and fax contact information would be the directive: Send by: above open boxes next to both Email and Fax, one or both of which is to be checked by the user. When he checks the Email and/or the Fax box, and then presses Enter, the letter is sent immediately.</p>

<p>If he also wants to send the letter to the media, he could then back up to the previous page and click on the Media button. If he would like a copy of the letter sent to his email address, a box could also be checked for that to occur. In just a few easy steps, that voter will have communicated fluently with his chosen national representatives and/or commentators and newspaper editors, and even have a copy to insert into a Political Folder of his own.</p>

<p>The same construction would apply to each political level of each user of the web site. After completing their national communications, the member would be encouraged to go to the next level--to their State, where one would see a whole new archived list of issues. They could respond or not, just as they did with national issues. Next they could view (and possibly respond to) their District issues, County issues and finally their City issues. At each political level, advertising relevant to that location would be inserted, just as it was at the National level.</p>

<h2>Discussion</h2>

<p>Because ItsYourIssue.com has an infinite number of issues to cover, we expect to attract an infinite number of users. We believe that as a result of its ease of use, we expect to be the "go-to" website for millions of working Americans that do not have the time, the knowledge of the issues, or the passion to dedicate themselves to activism. We also expect to see a good deal of cross-pollination, exposing users to a much broader array of issues and advertisers. It is unlikely that a person interested in Second Amendment rights would not be interested in Illegal Immigration issues, or even Health Care issues.</p>

<p>We believe that this novel concept, when implemented, will generate millions of page views a day by attracting virtually anyone who has even a passing interest in what government is doing. We are confident that this model will appeal to the broadest possible array of advertisers as well as users--national, state, district, county, and city. To our knowledge, this concept is new and innovative; and it affords investors the opportunity to make a very good return on investment by providing a service that is not available anywhere else.</p>

</div> <!-- end yui-g -->