<section class="accolades">
<div class="row">
	<h1>ACCOLADES</h1>
	<div class="pure-g">
		<article class="pure-u-1 pure-u-md-1-2">
			<p>Get ready! Get ready to experience how poems linking surprise to feeling fire-up your own creative synapses. These poems possess a <strong>crisp, bright</strong>, wetness – a delicious sense of Eros. Greensfelder's poems are exactly what one wants and expects when biting the apple, when living this whole life.<br />
			<span class="name">— John Fox, author of <em>Poetic Medicine: The Healing Art of Poem-Making</em> and Founder of The Institute for Poetic Medicine</span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2">
			<p>This delightful collection spans nearly 70 years of the poet's experience tasting apples in the Garden of her life, beginning with her earliest memories as a child of three and ending with observations about grandchildren. As good poetry should, <strong>these poems evoke insights about ourselves and the light and dark world</strong> of which we are all apple-biting by-products.<br />
			<span class="name">— Margaret Van Every, author of <em>A Pillow Stuffed with Diamonds</em> (2011) and <em>Saying Her Name</em> (2012)</span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2">
			<p>In this coming of age and beyond book, Greensfelder writes with humor and charm. Federico Garcia Lorca said the essence of poetry was in "el vulnerado." <em>Biting the Apple</em> reveals this vulnerability from the child who faces life's pain to the adult who finds survival skills. <em>Biting the Apple</em> is <strong>a delightful and moving verse memoir.</strong><br />
			<span class="name">— Glenna Luschei, Past Poet Laureate San Luis Obispo, Editor &amp; Publisher of <em>Solo Press</em></span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2">
			<p>In <em>Biting the Apple</em>, a collection of 50 poems, Jeanie Greensfelder explores her interior life as easily and fearlessly as one might explore the familiar interior of one's own house.  Intelligent, introspective, surprisingly funny, and compelling, it's <strong>like a freshly opened box of chocolates, begging us to read just one more</strong>. Greensfelder reveals herself in such a way that we can see our own souls reflected in hers, and thus recognize that we are all, as psychiatrist Harry Stack Sullivan said, "... simply much more human than otherwise."<br />
			<span class="name">— Susan Stewart, <em>Say It Right</em>, <em>Journal Plus</em> Reviewer</span></p>
		</article>
	</div>
</div>
</section>