<section class="book">
	<div class="row">
		<div class="pure-g">
			<div class="pure-u-1 pure-u-md-1-2 info">
				<a href="/books/biting-the-apple/" class="block include-link">
					<h1>Biting the Apple</h1>
					<h2>by Jeanie Greensfelder</h2>
				</a>
				<div class="details">
					<p class="price">$12.50 <a class="button" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=TCJUH4NNK6MRC">Buy now</a></p>
					<p>70 pages, Published December 2012</p>
				</div>
				<a href="/books/biting-the-apple/" class="block include-link">
					<p>Spanning seven decades, these intimate poems capture the human journey from the loss of innocence to the fullness of life. With humor and candor, Greensfelder evokes Joseph Campbell’s “sorrowful joys and joyful sorrows.”</p>
					<p class="learnmore">Learn more</p>
				</a>
			</div>
			<div class="pure-u-1 pure-u-md-1-2 cover">
				<a href="/books/biting-the-apple/" class="include-link">
					<img class="pure-img" src="/books/biting-the-apple/images/cover.jpg" alt="" />
				</a>
			</div>
		</div>
	</div>
</section>
