<section class="book">
	<div class="row">
		<div class="pure-g">
			<div class="pure-u-1 pure-u-md-1-2 info">
				<h1>Biting the Apple</h1>
				<h2>by Jeanie Greensfelder</h2>
				<div class="details">
					<p class="price">$12.50 <a class="button" href="#">Buy now</a></p>
					<p>70 pages, Published December 2012</p>
				</div>
				<p class="learnmore"><a href="/books/biting-the-apple/">Learn more</a></p>

			</div>
			<div class="pure-u-1 pure-u-md-1-2 cover">
				<img class="pure-img" src="/books/biting-the-apple/images/cover.jpg" alt="" />
			</div>
		</div>
	</div>
</section>
