<section class="smoky poem">
	<div class="row pure-g">
	<div class="pure-u-1 pure-u-md-1-2"></div>
	<div class="pure-u-1 pure-u-md-1-2">
		<h1>Smoky Mountain High</h1>
		<p>At daybreak in the Smokies<br />
		I saw my first fallen cloud. Mother <br />
		called it fog, but it looked like heaven <br />
		dropped down to look around.</p>

		<p>Billowing white beckoned,<br />
		if I could reach it before the sun <br />
		took heaven back to be<br />
		one more cloud in the sky.</p>
	</div>
	</div>
</section>	
