<section class="accolades">
<div class="row">
	<h1>ACCOLADES</h1>
	<div class="pure-g">
		<article class="pure-u-1 pure-u-md-1-2">
			<p>Ivan BrownOtter writes from experience, <strong>bringing the beauty and mystery of the Navajo Reservation to us</strong>. Whether he’s inside a lightning storm in a Navajo classroom or walking the mesa by moonlight, the experience is ours. <br />
		<span class="name">— Rosemary Wilvert, 2007 Poet Laureate, San Luis Obispo, California </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2">
			<p>Ivan explores the intuitive relationship between us, Native Americans and nature. Forget about punctuation and ride that <strong>mythical</strong> seam separating us from Nature and other creatures.<br />
			<span class="name">— Jerry Douglas Smith, Poet Laureate 2013, San Luis Obispo, CA  </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2">
			<p>Journey with Ivan through a blundering job interview on the Navajo Reservation. Enjoy a moonlight canyon walk or a run with the spirit of deer people. Ivan poetry is <strong>refreshingly simple, vibrant and candidly transparent</strong>. <br />
			<span class="name">— Alma Hernandez Wilson, Grant Writer, GUSD, Guadalupe, CA </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2">
			<p><strong>Fresh as a spring wind, clear as desert dawn, open as the night sky</strong>: Ivan BrownOtter’s poetry describes a world of remarkable beauty. You will come away feeling calmer, steadier, and wiser. <br />
			<span class="name">— Ken Solomon, Dept Head, Agricultural Engineering, CalPoly, SLO </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>Ivan’s poetry invites us to listen with simplicity and humor. It welcomes us to the heart, to the earth, and to our humanity, oftentimes filling us with serenity as we connect our physical and spiritual worlds.  <br />
		<span class="name">— Samuel H. Duarte, Poet and Author of Carnalval, Santa Maria, CA  </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>I first realized Ivan’s wit after I heard his poem about being mistaken for Christopher Lloyd. He’s a dead-ringer. Ivan writes with humor and passion. He is not a twist-the-words poet until you don’t even know the meaning. <br />
			<span class="name">— Laura, Big Sur Firefighter, Mother of new born Charlee, owner of Jake </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>Ivan takes us into the world of teaching children, hiking Navajo canyons and laughing at himself. The poems explore the mystical reality of our lives, others point us toward the moon.  There is great joy here and wisdom.<br />
			<span class="name">— Mike Heller, Professor of English, Roanoke College </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>Ivan BrownOtter exemplifies the power of writing from the heart. His poems will touch you as he ponders his physical and spiritual realms on the high mesas of Navajoland. <br />
			<span class="name">— Lynn Nelson, Professor of English, Arizona State Univ. (Emeritus) </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>The voice of Ivan BrownOtter couldn’t be more perfect for delivering the Native American wisdom he has gleaned from teaching in a Navaho school and from marinating in the culture. His vision is clear, his wry humor a gift. <br />
			<span class="name">— Jane Elsdon, San Luis Obispo Poet Laureate 2005 </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>Ivan leads us to where dreams and reality flow together in brilliant images of an introspective spirit world. Stripped of the white culture the poet enters the deepest silence of the Navajo Way and we go with him. Wonderful. <br />
			<span class="name">— Anne Candelaria, Poet Laureate 2002, San Luis Obispo, CA </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>Ivan tells us to write from the heart. These poems are right from the heart, his heart. Through his eyes we experience Mother Nature and native American culture up close and personal. Thanks for these heartfelt stories. <br />
			<span class="name">— Janejane </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>Had Hillerman chosen reservation school teachers rather than police officers as heroes for his novels, the stories of their lives, culture and struggles of Indian peoples no doubt would have followed Ivan BrownOtter’s path. <br />
			<span class="name">— Ed Musolff MBHS teacher and Cuesta CC Basketball Coach (Retired) </span></p>
		</article>

		<article class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
			<p>The dreams, the beauty, the history, the connections among all beings of our world—these are in Ivan’s book. Thank you for your thoughts on paper! <br />
			<span class="name">— Vera Wallen, Retired Superintendent of Schools</span></p>
		</article>
	</div>
</div>
</section>