<!--#set var="AMAZON-LINK" value="http://www.amazon.com/gp/product/1939502144/ref=as_li_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=1939502144&amp;linkCode=as2&amp;tag=penin-20&amp;linkId=GGQNBC2QEGNAJNSZ"-->

<section class="book">
	<div class="row">
		<div class="pure-g">
			<div class="pure-u-1 pure-u-md-1-2 info">
				<a href="<!--#echo var='AMAZON-LINK'-->" class="block include-link">
					<h1>Marriage and Other Leaps of Faith</h1>
					<h2>by Jeanie Greensfelder</h2>
				</a>
				<div class="details">
					<p class="price">$13.00 <a class="button" href="<!--#echo var='AMAZON-LINK'-->">Buy now at Amazon</a></p>
					<p>86 pages, Published March 2015</p>
				</div>
				<a href="<!--#echo var='AMAZON-LINK'-->" class="block include-link">
					<p>Amusing, candid, and engaging, <em>Marriage and Other Leaps of Faith</em> displays universal aspects of marriage and an exploration of this human journey in other life leaps.</p>
					<p>Greensfelder shows "...any long relationship can never be one thing at a time, only a counterpoint of feelings: resolute, funny, nostalgic, fearful, joyful and often astonishing." <small>(Diane Stevens)</small></p>
					<p class="learnmore">Buy now at Amazon</p>
				</a>
			</div>
			<div class="pure-u-1 pure-u-md-1-2 cover">
				<a href="<!--#echo var='AMAZON-LINK'-->" class="include-link">
					<img class="pure-img" src="/books/marriage-and-other-leaps-of-faith/images/cover.jpg" alt="" />
				</a>
			</div>
		</div>
	</div>
</section>

