<section class="future poem">
<div class="row">
<h1>BACK TO THE FUTURE</h1>
<h2>(The Junction Cafe, Chinle, Arizona)</h2>

<div class="pure-g">
	<div class="pure-u-1 pure-u-md-1-2">
	<p>
	A shy Navajo waitress asked<br />
	“Are you the ‘Back to the Future’ guy?”<br />

	With my white hair curling into the clouds <br />
	from the sides of my mostly bald head<br />
	I innocently said “Yeah me and Michael J Fox <br />
	been working on the flux capacitor<br />
	trying to generate some jig-a-watts<br />
	for the Delorian car”<br />
	<br />
	She told the other waitresses <br />
	and they believed her<br />
	They wanted my autograph<br />
	<br />
	“I’m not really him” I said “I was just pretending”
	</p>
	</div>

	<div class="pure-u-1 pure-u-md-1-2">
	<p>
	“No no you are him<br />
	We know you’re him” said another waitress<br />
	<br />
	“I’m just a teacher from Rough Rock School”<br />
	<br />
	She held out a pen and pad <br />
	“You can’t fool us<br />
	We’ve seen your movie ten times” <br />
	They stood there waiting<br />
	<br />
	I didn’t know what to do<br />
	I signed Christopher Lloyd
	</p>
	</div>
</div>
</div>
</section>