<section class="book">
	<div class="row">
		<div class="pure-g">
			<div class="pure-u-1 pure-u-md-1-2 info">
				<h1>Crossing the Plateau</h1>
				<h2>by Ivan BrownOtter</h2>
				<div class="details">
					<p class="price">$12.50 <a class="button" href="#">Buy now</a></p>
					<p>76 pages, Published May 2013</p> 
				</div>
				<p class="learnmore"><a href="/books/crossing-the-plateau/">Learn more</a></p>
			</div>
			<div class="pure-u-1 pure-u-md-1-2 cover">
				<img class="pure-img" src="/books/crossing-the-plateau/images/cover.jpg" alt="" />
			</div>
		</div>
	</div>
</section>