<section class="indian-time poem">
<div class="row">
<h1>Indian Time</h1>

<div class="pure-g">
	<div class="pure-u-1 pure-u-md-1-2">
	<p>“You are a day and five hours late <br />
	for this interview” said the superintendent <br />
	at the Navajo school “How come?”</p>

	<p>I looked at him and took a breath<br />
	as if to say <em>Well shit, Mr Superintendent<br />
	There are no street signs <br />
	How did you expect me to find the place<br />
	I’m not Superman<br />
	Global positioning hasn’t arrived yet</em></p>

	<p><em>Sandy roads curve in and out of rainbow clouds<br />
	circle back through red rock canyons <br />
	I can’t tell an Indian road from a sandstone pathway</em></p>
	</div>

	<div class="pure-u-1 pure-u-md-1-2">
	<p><em>I ended up in Lukachukai then Chilchinbeto<br />
	without knowing how I got there<br />
	I slept out in the middle of nowhere <br />
	under a gallery of glacial-blue stars</em> </p>

	<p>But I didn’t say it out loud<br />
	Instead I said “I’m from Phoenix<br />
	You can’t get here from there”</p>

	<p>The superintendent laughed <br />
	“You’re right about that  <br />
	Several people applied for this position<br />
	but you’re the only one who showed-up<br />
	You’re our new English teacher<br />
	Looks like you’re already on Indian time”</p>
	</div>
</div>
</div>
</section>