<section class="future poem">
<div class="row">
<h1>Moon is Crossing the Sky</h1>

<div class="pure-g">
	<div class="pure-u-1 pure-u-md-1-2">
	<p>December warms like spring <br />
	Light breeze stirs<br />
	the Hopi star-filled sky<br />
	A thousand tiny points of light <br />
	blaze down on planet Earth</p>

	<p>The dog Maassu leads the way<br />
	a winding path of sage and sand <br />
	yucca of a hundred swords<br />
	and shifting snakeweed shadows</p>
	</div>

	<div class="pure-u-1 pure-u-md-1-2">	
	<p>up the mesa toward the Moon <br />
	into a gathering of pinyon pine <br />
	and purple-green prickly pear</p>

	<p>I’m going home, Grandfather <br />
	and Moon is crossing the sky</p>
	</div>
</div>
</div>
</section>