<section class="indian-time poem">
<div class="row">
<h1>Opening Their Journals at the Navajo School</h1>

<div class="pure-g">
	<div class="pure-u-1 pure-u-md-1-2">
		<p>A ghostly gray cloud slowly swallows the sky<br />
		Cool air rushes in <br />
		fresh with the scent of juniper soil</p>

		<p>Suddenly the classroom explodes with light <br />
		The brazen crash ... a lightning strike<br />
		Zigzags of fire hiss like snakes<br />
		Ozone’s sour tongue licks the air	<br />
		The roar of a freight train<br />
		comes barreling straight down</p>

		<p>Kids rush to the windows<br />
		Glowing marbles pour out of the sky<br />
		bouncing big as hominy corn<br />
		rumble the canyon like kettle drums<br />
		and paint a path of summer white<br />
		out across the plateau</p>
	</div>
	<div class="pure-u-1 pure-u-md-1-2">
		<p>With my ears still ringing <br />
		I whisper to the class<br />
		“Take out your journals<br />
		It’s time to write”</p>

		<p>Some stay at the windows<br />
		Others sit on the floor <br />
		opening their journals <br />
		to the storm</p>
	</div>
</div>
</div>
</section>