"<em>Rock &amp; Fire</em>, the landmark book by SLO County Poet Laureate Marguerite Costigan is as burning as creation itself, as solid as granite. This book makes you proud to be a celebrant of the genesis of poetry and a survivor of the Big Bang."
— Glenna Luschei, Owner/Publisher, Solo Press

"And at last we hold in our hands a book of poems as weighty as stone, outcroppings from what lies beneath, within the soul and upon the earth; these poems are cairns."
— Marsha de la O, author of <em>Antidote for Night</em>

"The poems in <em>Rock &amp; Fire</em> by Marguerite Costigan shatter our place in the world. We are changed by this storm of words, this raw power..."
— Kevin Patrick Sullivan, co-founder of the San Luis Obispo Poetry Festival (1982 to present)

"Marguerite Costigan writes like a force of nature, because that's exactly what she is: woman/poet/planet, laying bare the metamorphic inwardness of elements and beings, by means of language forged in fire."
— Maia, author of <em>The SpiritLife of Birds</em>

"The first time I heard Marguerite Costigan read her poems everything else in the room got still like the air does before an earthquake. It was clear, I was in the presence of a rare one — rare poet, rare human. She adds heft to my spirit. These are poems as sturdy as mountains, bless-ed as wind."
— Patrice Vecchione, author of <em>Step into Nature: Nurturing Imagination and Spirit in Everyday Life</em>