<section class="book">
	<div class="row">
		<div class="pure-g">
			<div class="pure-u-1 pure-u-md-1-2 info">
				<h1>Rock &amp; Fire</h1>
				<h2>by Marguerite Costigan</h2>
				<div class="details">
					<p class="price">$13.95 <a class="button" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=7SBHYZ7YQ8DY4">Buy now</a></p>
					<p>73 pages, Published February 2016</p> 
				</div>
				<p>The latest book by 2015-2016 San Luis Obispo County Poet Laureate, this sizzling collection "is as burning as creation itself, as solid as granite." <small>(Glenna Luschei)</small></p> 
				<p class="learnmore"><a href="http://www.amazon.com/gp/product/1939502179">Learn more at Amazon</a></p>
			</div>
			<div class="pure-u-1 pure-u-md-1-2 cover">
				<img class="pure-img" src="/books/rock-and-fire/images/cover.jpg" alt="" />
			</div>
		</div>
	</div>
</section>