

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
    <div id="layout">
    <!-- Menu toggle -->
    <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
    </a>

    <div id="menu">
        <div class="pure-menu pure-menu-open pure-menu-horizontal">
            <a class="pure-menu-heading" href="/"><img class="logo" src="/img/logo.png" width="30" height="30" alt="" /></a>
            <ul>
                <li>Magazine: <a href="http://ifwhen.us"><em>if&amp;when</em></a></li>
                <li>Books: <a href="/books/biting-the-apple/">Biting the Apple</a>, <a href="/books/crossing-the-plateau/">Crossing the Plateau</a></li>
            </ul>
        </div>
    </div>

    <div id="main">